name: Deploy to Prod

on:
    push:
        branches:
            - main

env:
    ENV: prod

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 소스 레포
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set variables
              run: |
                  TAG=$(git describe --tags --abbrev=0)
                  SHA=$(git rev-parse --short=6 HEAD)
                  echo "IMAGE_TAG=${ENV}-${TAG}-${SHA}" >> $GITHUB_ENV

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to ECR
              run: |
                  aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
                  docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            - name: Build & Push image
              run: |
                  docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
                  docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
                  docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

            - name: Install yq
              run: |
                  sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
                  sudo chmod +x /usr/bin/yq

            - name: Clone GitOps Repository
              uses: actions/checkout@v3
              with:
                  repository: 100-hours-a-week/20-real-gitops
                  token: ${{ secrets.GITOPS_TOKEN }}
                  path: gitops

            - name: Update image tag in values-prod.yaml
              run: |
                  cd gitops/env/prod/spring
                  yq e '.image.tag = "${{ env.IMAGE_TAG }}"' -i values-prod.yaml

            - name: Commit & Push changes
              run: |
                  cd gitops
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git add env/prod/spring/values-prod.yaml
                  git commit -m "chore: Update spring-prod image tag to $IMAGE_TAG"
                  git push origin main
